sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g npm@latest
script:
  - npm run ci
notifications:
  slack:
    rooms:
      - secure: UhksUyNdKmzosK2OoFqiEOAlkC6gOXMnum1yuU7jSGONz+boObWNju3fKKl2+4FLIv2nYKu4ne73oM1Bu+kqxhFBNEdDAgFRriulz4Eu6B0h60FNMUxHKTKqvY7TRM3HJiFL0OKTWaL7qMHvZ+8ecZbviMYqo7uk60vtY7G60dzTmywGtNhDwCAagPjmipqqdyXcLaWJkO1OELoYb1TBYTOFGb1zkyvQw4dcRBYyN4XbK1aE5bjxSI9toclGsWKV8BctY3H8alqKtdFkAsVjfCAgErZFxgTnagbIkARvcPMYrcoB21jAZy08cL7dpy2mGdIlmzYsbnQbdhqYYl1w2OWvzPUR+a2QGsTzKfFdi6J05zpXIJSt5HY1aL50x/RYeyVJV8iU6ey+0A3gndOkeFqDgIhQsLg6XWzTdqwygIztkHFrfQQ2wxj7AYt7xNr7qpucZWw0pbWMld2DXjrHcWFYCDpbLnFs8YvRtCTvJs0MDieUUDC2o6TffSrlaT63we+aL+gDEuVDJfCs0uQMipY4fdTWUsAtpLjWaeva4hDckdeYbw1nIgyZrZVERgJsRFgf5EM5Nmp7GqICOppvg0Z6nGKx04BaoWOTww9K6P8MXKZsDGWkqhlmWVd+WcpPnASUsKaIMQpZc54yCGz/upZQyxVhIsEajyjRsB9ej6E=
    on_success: change
